In [5]:
import json
import pandas
import numpy

with open("kraken.json", "r") as file:
    OHLCs= json.load(file)
weeklyCandles = OHLCs["result"]["604800"]

In [2]:
df = pandas.DataFrame(weeklyCandles, columns= ["CloseTime", "OpenPrice", "HighPrice", "LowPrice", "ClosePrice", "?","Volume"])
df['CloseTime'] = pandas.to_datetime(df['CloseTime'],unit='s')

In [40]:
df[df["ClosePrice"] > 0]

,CloseTime,OpenPrice,HighPrice,LowPrice,ClosePrice,?,Volume
0,2013-10-17,125.85000,153.00000,125.85000,138.09000,42.634753,0.000000e+00
1,2013-10-24,138.09000,203.45000,137.52000,203.45000,171.619985,0.000000e+00
2,2013-10-31,203.45000,207.30246,169.92010,203.77000,242.176755,0.000000e+00
3,2013-11-07,203.77000,269.42566,199.00000,263.73672,198.738897,0.000000e+00
4,2013-11-14,263.73672,500.00000,262.86280,398.00000,194.705865,0.000000e+00
5,2013-11-21,398.00000,800.00000,125.85000,591.81000,1941.330677,0.000000e+00
6,2013-11-28,591.81000,1081.09181,583.11045,994.95000,217.660990,0.000000e+00
7,2013-12-05,994.95000,1198.80090,770.00000,1079.93122,243.637714,0.000000e+00
8,2013-12-12,1079.93122,1110.00000,600.96141,883.78144,471.826244,0.000000e+00
9,2013-12-19,883.78144,919.07787,380.00000,528.00000,420.314543,0.000000e+00
10,2013-12-26,528.00000,718.21618,517.62147,676.00000,203.182475,0.000000e+00
11,2014-01-02,676.00000,771.00000,676.00000,753.99000,143.362573,0.000000e+00
12,2014-01-09,753.99000,1019.00000,750.00000,824.98287,327.371699,0.000000e+00
13,2014-01-16,824.98287,918.05471,805.00000,850.00364,124.600135,0.000000e+00
14,2014-01-23,850.00364,865.00000,788.00000,830.88999,98.722722,0.000000e+00
15,2014-01-30,830.88999,840.00000,775.00000,795.00000,123.466946,0.000000e+00
16,2014-02-06,795.00000,835.00000,787.01000,802.50000,88.892335,0.000000e+00
17,2014-02-13,802.50000,803.72713,550.00000,670.66590,248.578658,0.000000e+00
18,2014-02-20,670.66590,710.00000,586.43000,630.16179,191.002755,0.000000e+00
19,2014-02-27,630.16179,650.27996,450.00000,587.27133,308.416627,0.000000e+00
20,2014-03-06,587.27133,720.00000,550.00000,680.99000,186.086561,0.000000e+00
21,2014-03-13,680.99000,693.00000,550.27500,632.31094,57.594682,0.000000e+00
22,2014-03-20,632.31094,657.99101,550.00000,620.06200,56.322153,0.000000e+00
23,2014-03-27,620.06200,641.14149,554.05000,585.08510,61.999582,0.000000e+00
24,2014-04-03,585.08510,599.27378,436.07375,443.62500,168.589143,0.000000e+00
25,2014-04-10,443.62500,550.00000,426.45421,452.99853,54.424047,0.000000e+00
26,2014-04-17,452.99853,583.75327,353.75804,523.53017,178.330220,0.000000e+00
27,2014-04-24,523.53017,530.35862,477.19035,495.61699,91.920803,0.000000e+00
28,2014-05-01,495.61699,503.48132,429.08540,448.34318,59.749166,0.000000e+00
29,2014-05-08,448.34318,464.41767,422.19000,441.88615,63.624863,0.000000e+00
...,...,...,...,...,...,...,...
244,2018-06-28,6762.70000,6787.60000,5650.00000,6134.20000,34859.414000,2.151124e+08
245,2018-07-05,6132.50000,6790.00000,5787.70000,6584.20000,24165.225000,1.524892e+08
246,2018-07-12,6587.00000,6838.50000,6276.70000,6377.90000,18601.557000,1.218713e+08
247,2018-07-19,6378.00000,7599.00000,6073.30000,7379.90000,29177.557000,1.967354e+08
248,2018-07-26,7379.80000,8496.60000,7200.30000,8166.00000,33411.094000,2.596421e+08
249,2018-08-02,8164.70000,8315.00000,7423.00000,7604.10000,28792.193000,2.290444e+08
250,2018-08-09,7469.40000,7533.40000,6120.00000,6275.90000,28322.300000,1.931755e+08
251,2018-08-16,6276.60000,6740.90000,5890.00000,6269.50000,48233.390000,3.031009e+08
252,2018-08-23,6269.50000,6916.50000,6210.00000,6350.00000,28009.752000,1.808012e+08
253,2018-08-30,6349.30000,7133.70000,6329.20000,7022.70000,21749.104000,1.472240e+08
254,2018-09-06,7025.40000,7405.90000,6638.80000,6684.50000,26651.309000,1.887354e+08
255,2018-09-13,6684.40000,6702.30000,6073.90000,6319.50000,29986.746000,1.901715e+08
256,2018-09-20,6325.10000,6599.80000,6102.60000,6391.00000,24917.318000,1.596536e+08
257,2018-09-27,6390.60000,6836.40000,6318.50000,6453.50000,25735.605000,1.689247e+08
258,2018-10-04,6452.00000,6796.20000,6397.60000,6463.90000,22517.820000,1.476241e+08
259,2018-10-11,6461.10000,6688.30000,6441.80000,6530.40000,12572.724000,8.248058e+07
260,2018-10-18,6530.10000,6820.00000,6091.20000,6442.50000,27029.898000,1.717334e+08
261,2018-10-25,6442.30000,6487.90000,6344.60000,6413.90000,9477.000000,6.072514e+07
262,2018-11-01,6414.00000,6450.00000,6201.00000,6307.50000,15769.681925,9.961319e+07
263,2018-11-08,6307.50000,6552.90000,6290.60000,6503.30000,11864.286429,7.598194e+07
264,2018-11-15,6503.20000,6515.70000,5330.00000,5602.70000,26395.230616,1.579890e+08
265,2018-11-22,5600.90000,5698.00000,4028.80000,4548.20000,71531.544944,3.492645e+08
266,2018-11-29,4543.30000,4589.90000,3456.00000,4219.80000,92594.974354,3.645870e+08
267,2018-12-06,4219.80000,4441.00000,3653.00000,3688.00000,67825.398794,2.720380e+08
268,2018-12-13,3697.10000,3851.10000,3208.00000,3435.20000,80311.656296,2.779587e+08
269,2018-12-20,3433.10000,3920.00000,3120.00000,3683.60000,86203.522051,2.984856e+08
270,2018-12-27,3682.00000,4239.90000,3651.00000,3808.20000,89431.537098,3.519755e+08
271,2019-01-03,3809.20000,4499.30000,3565.90000,3886.20000,47955.599602,1.809633e+08
272,2019-01-10,3887.80000,4113.90000,3721.90000,3999.90000,40984.295464,1.612948e+08
273,2019-01-17,4002.20000,4035.50000,3375.00000,3535.70000,33216.180504,1.215143e+08

In [12]:
df.describe()

,OpenPrice,HighPrice,LowPrice,ClosePrice,?,Volume
count,274.000000,274.000000,274.000000,274.000000,274.000000,2.740000e+02
mean,2481.094955,2729.693146,2230.574584,2493.863308,18352.965161,6.942810e+07
std,3433.146162,3832.485226,3020.144892,3431.651581,25531.696066,1.588357e+08
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,396.912500,426.760500,357.871807,402.472497,195.759271,0.000000e+00
50%,631.405470,678.454490,590.741500,633.795470,6924.516750,0.000000e+00
75%,3876.300000,4239.975000,3507.825000,3877.425000,28854.578000,0.000000e+00
max,16217.700000,19660.000000,15501.200000,16220.700000,198105.700000,8.925572e+08

In [41]:
df[df["?"]!=198105.7]

,CloseTime,OpenPrice,HighPrice,LowPrice,ClosePrice,?,Volume
0,2013-10-17,125.85000,153.00000,125.85000,138.09000,42.634753,0.000000e+00
1,2013-10-24,138.09000,203.45000,137.52000,203.45000,171.619985,0.000000e+00
2,2013-10-31,203.45000,207.30246,169.92010,203.77000,242.176755,0.000000e+00
3,2013-11-07,203.77000,269.42566,199.00000,263.73672,198.738897,0.000000e+00
4,2013-11-14,263.73672,500.00000,262.86280,398.00000,194.705865,0.000000e+00
5,2013-11-21,398.00000,800.00000,125.85000,591.81000,1941.330677,0.000000e+00
6,2013-11-28,591.81000,1081.09181,583.11045,994.95000,217.660990,0.000000e+00
7,2013-12-05,994.95000,1198.80090,770.00000,1079.93122,243.637714,0.000000e+00
8,2013-12-12,1079.93122,1110.00000,600.96141,883.78144,471.826244,0.000000e+00
9,2013-12-19,883.78144,919.07787,380.00000,528.00000,420.314543,0.000000e+00
10,2013-12-26,528.00000,718.21618,517.62147,676.00000,203.182475,0.000000e+00
11,2014-01-02,676.00000,771.00000,676.00000,753.99000,143.362573,0.000000e+00
12,2014-01-09,753.99000,1019.00000,750.00000,824.98287,327.371699,0.000000e+00
13,2014-01-16,824.98287,918.05471,805.00000,850.00364,124.600135,0.000000e+00
14,2014-01-23,850.00364,865.00000,788.00000,830.88999,98.722722,0.000000e+00
15,2014-01-30,830.88999,840.00000,775.00000,795.00000,123.466946,0.000000e+00
16,2014-02-06,795.00000,835.00000,787.01000,802.50000,88.892335,0.000000e+00
17,2014-02-13,802.50000,803.72713,550.00000,670.66590,248.578658,0.000000e+00
18,2014-02-20,670.66590,710.00000,586.43000,630.16179,191.002755,0.000000e+00
19,2014-02-27,630.16179,650.27996,450.00000,587.27133,308.416627,0.000000e+00
20,2014-03-06,587.27133,720.00000,550.00000,680.99000,186.086561,0.000000e+00
21,2014-03-13,680.99000,693.00000,550.27500,632.31094,57.594682,0.000000e+00
22,2014-03-20,632.31094,657.99101,550.00000,620.06200,56.322153,0.000000e+00
23,2014-03-27,620.06200,641.14149,554.05000,585.08510,61.999582,0.000000e+00
24,2014-04-03,585.08510,599.27378,436.07375,443.62500,168.589143,0.000000e+00
25,2014-04-10,443.62500,550.00000,426.45421,452.99853,54.424047,0.000000e+00
26,2014-04-17,452.99853,583.75327,353.75804,523.53017,178.330220,0.000000e+00
27,2014-04-24,523.53017,530.35862,477.19035,495.61699,91.920803,0.000000e+00
28,2014-05-01,495.61699,503.48132,429.08540,448.34318,59.749166,0.000000e+00
29,2014-05-08,448.34318,464.41767,422.19000,441.88615,63.624863,0.000000e+00
...,...,...,...,...,...,...,...
244,2018-06-28,6762.70000,6787.60000,5650.00000,6134.20000,34859.414000,2.151124e+08
245,2018-07-05,6132.50000,6790.00000,5787.70000,6584.20000,24165.225000,1.524892e+08
246,2018-07-12,6587.00000,6838.50000,6276.70000,6377.90000,18601.557000,1.218713e+08
247,2018-07-19,6378.00000,7599.00000,6073.30000,7379.90000,29177.557000,1.967354e+08
248,2018-07-26,7379.80000,8496.60000,7200.30000,8166.00000,33411.094000,2.596421e+08
249,2018-08-02,8164.70000,8315.00000,7423.00000,7604.10000,28792.193000,2.290444e+08
250,2018-08-09,7469.40000,7533.40000,6120.00000,6275.90000,28322.300000,1.931755e+08
251,2018-08-16,6276.60000,6740.90000,5890.00000,6269.50000,48233.390000,3.031009e+08
252,2018-08-23,6269.50000,6916.50000,6210.00000,6350.00000,28009.752000,1.808012e+08
253,2018-08-30,6349.30000,7133.70000,6329.20000,7022.70000,21749.104000,1.472240e+08
254,2018-09-06,7025.40000,7405.90000,6638.80000,6684.50000,26651.309000,1.887354e+08
255,2018-09-13,6684.40000,6702.30000,6073.90000,6319.50000,29986.746000,1.901715e+08
256,2018-09-20,6325.10000,6599.80000,6102.60000,6391.00000,24917.318000,1.596536e+08
257,2018-09-27,6390.60000,6836.40000,6318.50000,6453.50000,25735.605000,1.689247e+08
258,2018-10-04,6452.00000,6796.20000,6397.60000,6463.90000,22517.820000,1.476241e+08
259,2018-10-11,6461.10000,6688.30000,6441.80000,6530.40000,12572.724000,8.248058e+07
260,2018-10-18,6530.10000,6820.00000,6091.20000,6442.50000,27029.898000,1.717334e+08
261,2018-10-25,6442.30000,6487.90000,6344.60000,6413.90000,9477.000000,6.072514e+07
262,2018-11-01,6414.00000,6450.00000,6201.00000,6307.50000,15769.681925,9.961319e+07
263,2018-11-08,6307.50000,6552.90000,6290.60000,6503.30000,11864.286429,7.598194e+07
264,2018-11-15,6503.20000,6515.70000,5330.00000,5602.70000,26395.230616,1.579890e+08
265,2018-11-22,5600.90000,5698.00000,4028.80000,4548.20000,71531.544944,3.492645e+08
266,2018-11-29,4543.30000,4589.90000,3456.00000,4219.80000,92594.974354,3.645870e+08
267,2018-12-06,4219.80000,4441.00000,3653.00000,3688.00000,67825.398794,2.720380e+08
268,2018-12-13,3697.10000,3851.10000,3208.00000,3435.20000,80311.656296,2.779587e+08
269,2018-12-20,3433.10000,3920.00000,3120.00000,3683.60000,86203.522051,2.984856e+08
270,2018-12-27,3682.00000,4239.90000,3651.00000,3808.20000,89431.537098,3.519755e+08
271,2019-01-03,3809.20000,4499.30000,3565.90000,3886.20000,47955.599602,1.809633e+08
272,2019-01-10,3887.80000,4113.90000,3721.90000,3999.90000,40984.295464,1.612948e+08
273,2019-01-17,4002.20000,4035.50000,3375.00000,3535.70000,33216.180504,1.215143e+08

In [42]:
df

,CloseTime,OpenPrice,HighPrice,LowPrice,ClosePrice,?,Volume
0,2013-10-17,125.85000,153.00000,125.85000,138.09000,42.634753,0.000000e+00
1,2013-10-24,138.09000,203.45000,137.52000,203.45000,171.619985,0.000000e+00
2,2013-10-31,203.45000,207.30246,169.92010,203.77000,242.176755,0.000000e+00
3,2013-11-07,203.77000,269.42566,199.00000,263.73672,198.738897,0.000000e+00
4,2013-11-14,263.73672,500.00000,262.86280,398.00000,194.705865,0.000000e+00
5,2013-11-21,398.00000,800.00000,125.85000,591.81000,1941.330677,0.000000e+00
6,2013-11-28,591.81000,1081.09181,583.11045,994.95000,217.660990,0.000000e+00
7,2013-12-05,994.95000,1198.80090,770.00000,1079.93122,243.637714,0.000000e+00
8,2013-12-12,1079.93122,1110.00000,600.96141,883.78144,471.826244,0.000000e+00
9,2013-12-19,883.78144,919.07787,380.00000,528.00000,420.314543,0.000000e+00
10,2013-12-26,528.00000,718.21618,517.62147,676.00000,203.182475,0.000000e+00
11,2014-01-02,676.00000,771.00000,676.00000,753.99000,143.362573,0.000000e+00
12,2014-01-09,753.99000,1019.00000,750.00000,824.98287,327.371699,0.000000e+00
13,2014-01-16,824.98287,918.05471,805.00000,850.00364,124.600135,0.000000e+00
14,2014-01-23,850.00364,865.00000,788.00000,830.88999,98.722722,0.000000e+00
15,2014-01-30,830.88999,840.00000,775.00000,795.00000,123.466946,0.000000e+00
16,2014-02-06,795.00000,835.00000,787.01000,802.50000,88.892335,0.000000e+00
17,2014-02-13,802.50000,803.72713,550.00000,670.66590,248.578658,0.000000e+00
18,2014-02-20,670.66590,710.00000,586.43000,630.16179,191.002755,0.000000e+00
19,2014-02-27,630.16179,650.27996,450.00000,587.27133,308.416627,0.000000e+00
20,2014-03-06,587.27133,720.00000,550.00000,680.99000,186.086561,0.000000e+00
21,2014-03-13,680.99000,693.00000,550.27500,632.31094,57.594682,0.000000e+00
22,2014-03-20,632.31094,657.99101,550.00000,620.06200,56.322153,0.000000e+00
23,2014-03-27,620.06200,641.14149,554.05000,585.08510,61.999582,0.000000e+00
24,2014-04-03,585.08510,599.27378,436.07375,443.62500,168.589143,0.000000e+00
25,2014-04-10,443.62500,550.00000,426.45421,452.99853,54.424047,0.000000e+00
26,2014-04-17,452.99853,583.75327,353.75804,523.53017,178.330220,0.000000e+00
27,2014-04-24,523.53017,530.35862,477.19035,495.61699,91.920803,0.000000e+00
28,2014-05-01,495.61699,503.48132,429.08540,448.34318,59.749166,0.000000e+00
29,2014-05-08,448.34318,464.41767,422.19000,441.88615,63.624863,0.000000e+00
...,...,...,...,...,...,...,...
244,2018-06-28,6762.70000,6787.60000,5650.00000,6134.20000,34859.414000,2.151124e+08
245,2018-07-05,6132.50000,6790.00000,5787.70000,6584.20000,24165.225000,1.524892e+08
246,2018-07-12,6587.00000,6838.50000,6276.70000,6377.90000,18601.557000,1.218713e+08
247,2018-07-19,6378.00000,7599.00000,6073.30000,7379.90000,29177.557000,1.967354e+08
248,2018-07-26,7379.80000,8496.60000,7200.30000,8166.00000,33411.094000,2.596421e+08
249,2018-08-02,8164.70000,8315.00000,7423.00000,7604.10000,28792.193000,2.290444e+08
250,2018-08-09,7469.40000,7533.40000,6120.00000,6275.90000,28322.300000,1.931755e+08
251,2018-08-16,6276.60000,6740.90000,5890.00000,6269.50000,48233.390000,3.031009e+08
252,2018-08-23,6269.50000,6916.50000,6210.00000,6350.00000,28009.752000,1.808012e+08
253,2018-08-30,6349.30000,7133.70000,6329.20000,7022.70000,21749.104000,1.472240e+08
254,2018-09-06,7025.40000,7405.90000,6638.80000,6684.50000,26651.309000,1.887354e+08
255,2018-09-13,6684.40000,6702.30000,6073.90000,6319.50000,29986.746000,1.901715e+08
256,2018-09-20,6325.10000,6599.80000,6102.60000,6391.00000,24917.318000,1.596536e+08
257,2018-09-27,6390.60000,6836.40000,6318.50000,6453.50000,25735.605000,1.689247e+08
258,2018-10-04,6452.00000,6796.20000,6397.60000,6463.90000,22517.820000,1.476241e+08
259,2018-10-11,6461.10000,6688.30000,6441.80000,6530.40000,12572.724000,8.248058e+07
260,2018-10-18,6530.10000,6820.00000,6091.20000,6442.50000,27029.898000,1.717334e+08
261,2018-10-25,6442.30000,6487.90000,6344.60000,6413.90000,9477.000000,6.072514e+07
262,2018-11-01,6414.00000,6450.00000,6201.00000,6307.50000,15769.681925,9.961319e+07
263,2018-11-08,6307.50000,6552.90000,6290.60000,6503.30000,11864.286429,7.598194e+07
264,2018-11-15,6503.20000,6515.70000,5330.00000,5602.70000,26395.230616,1.579890e+08
265,2018-11-22,5600.90000,5698.00000,4028.80000,4548.20000,71531.544944,3.492645e+08
266,2018-11-29,4543.30000,4589.90000,3456.00000,4219.80000,92594.974354,3.645870e+08
267,2018-12-06,4219.80000,4441.00000,3653.00000,3688.00000,67825.398794,2.720380e+08
268,2018-12-13,3697.10000,3851.10000,3208.00000,3435.20000,80311.656296,2.779587e+08
269,2018-12-20,3433.10000,3920.00000,3120.00000,3683.60000,86203.522051,2.984856e+08
270,2018-12-27,3682.00000,4239.90000,3651.00000,3808.20000,89431.537098,3.519755e+08
271,2019-01-03,3809.20000,4499.30000,3565.90000,3886.20000,47955.599602,1.809633e+08
272,2019-01-10,3887.80000,4113.90000,3721.90000,3999.90000,40984.295464,1.612948e+08
273,2019-01-17,4002.20000,4035.50000,3375.00000,3535.70000,33216.180504,1.215143e+08